package exceptions;

/**
 * TaskDoneException is thrown when done command is
 * given to a task that is already done.
 */
public class TaskDoneException extends Exception {
}
